/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.virtusa.sonarqexp;
import java.util.logging.Level;
import java.util.logging.Logger;

public class App {
    public String getGreeting() {
        return "Hello world.";
    }

    public static void main(String[] args) {
        //System.out.println(new App().getGreeting());
		logger.log(new App().getGreeting());
    }
}
